### ISSUE TITLE
Extend profit tracking to check gems

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyBackendForFrontend#3]
Gemstones can be taken out of items and sold individually on bazaar.
The profit calculation should account for that.

**Comment by TGWaffles** [comment]
Possibly take into account that removing gemstones also costs coins:

Rough | 1
Flawed | 100
Fine | 10,000
Flawless | 100,000
Perfect | 500,000
[source](https://hypixel-skyblock.fandom.com/wiki/Geo#Removing_Gemstones)

**Comment by Ekwav** [comment]
Done
